"Filed out from Dolphin Smalltalk 7"!

Object subclass: #SharedPool
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SharedPool guid: (GUID fromString: '{d558d8a4-f840-458d-b100-f071e85ea157}')!
SharedPool comment: ''!
!SharedPool categoriesForClass!Collections-Unordered! !
!SharedPool class methodsFor!

associationsDo: aBlock

	^self classPool associationsDo: aBlock! !
!SharedPool class categoriesFor: #associationsDo:!public! !

