"Filed out from Dolphin Smalltalk 7"!

Object subclass: #UIManager
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UIManager guid: (GUID fromString: '{7e926003-9032-4433-be52-b378c08ef2f6}')!
UIManager comment: ''!
!UIManager categoriesForClass!Kernel-Objects! !
!UIManager class methodsFor!

default

	^self!

textEntry: aQuestion

	^Prompter prompt: aQuestion! !
!UIManager class categoriesFor: #default!public! !
!UIManager class categoriesFor: #textEntry:!public! !

