"Filed out from Dolphin Smalltalk 7"!

Object subclass: #CurrentExecutionEnvironment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CurrentExecutionEnvironment guid: (GUID fromString: '{11d7be37-5621-414d-82c4-eb9f9770af79}')!
CurrentExecutionEnvironment comment: ''!
!CurrentExecutionEnvironment categoriesForClass!Kernel-Objects! !
!CurrentExecutionEnvironment class methodsFor!

runTestsBy: aBlock

	aBlock value! !
!CurrentExecutionEnvironment class categoriesFor: #runTestsBy:!public! !

