"Filed out from Dolphin Smalltalk 7"!

Object subclass: #RPackageOrganizer
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
RPackageOrganizer guid: (GUID fromString: '{f89c5606-8d11-4b29-832b-da18cd4545ec}')!
RPackageOrganizer comment: ''!
!RPackageOrganizer categoriesForClass!Kernel-Objects! !
!RPackageOrganizer class methodsFor!

default

	^Package manager! !
!RPackageOrganizer class categoriesFor: #default!public! !

