"Filed out from Dolphin Smalltalk 7"!

Object subclass: #TestAsserter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
TestAsserter guid: (GUID fromString: '{f3c7952b-e31c-4f32-a0c2-198aeeb8dc25}')!
TestAsserter comment: ''!
!TestAsserter categoriesForClass!Kernel-Objects! !
!TestAsserter class methodsFor!

classForTestResult
	"Returns the class of the test result"
	^ TestResult! !
!TestAsserter class categoriesFor: #classForTestResult!public! !

