"Filed out from Dolphin Smalltalk"!

Array variableSubclass: #TraitArray
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

TraitArray guid: (GUID fromString: '{265c01cb-170a-4c90-b458-17df819f6f71}')!

TraitArray comment: ''!

!TraitArray categoriesForClass!Collections-Arrayed! !

!TraitArray methodsFor!

+ aTraitClass

	^self, {aTraitClass}! !

!TraitArray categoriesForMethods!
+!public! !
!

