"Filed out from Dolphin Smalltalk 7"!

Trait subclass: #TraitTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
TraitTest guid: (GUID fromString: '{7f278b91-1a41-436a-9f1e-066662b3720d}')!
TraitTest comment: ''!
!TraitTest categoriesForClass!Kernel-Objects! !
!TraitTest methodsFor!

thisIsATest! !
!TraitTest categoriesFor: #thisIsATest!public! !

